### ISSUE TITLE
Feedback for First Model/Views

### ISSUE THREAD

**Issue by david-at-ocs** [david-at-ocs/06-23-beer-ratings#11]

**Comment by sumeetjain** [comment]
- [x] Change your module's `find` method so that it returns an object. You shouldn't really need a `find_as_object` method in each of your classes (even though I know that's one of the ways I demonstrated it in class).
- [x] [This](https://github.com/david-at-ocs/06-23-beer-ratings/blob/master/models/beer.rb#L61) could itself be a method – maybe `valid?`.
- [x] [This relative path](https://github.com/david-at-ocs/06-23-beer-ratings/blob/master/views/beers/beer_added.erb#L5) makes the view brittle: If you change the path by which that view gets loaded, that `href` won't work anymore. Use `/homepage` instead, since that'll always mean the same thing.

**Comment by david-at-ocs** [comment]
Think I took care of everything.

**Comment by sumeetjain** [comment]
- [x] When you use [this module](https://github.com/david-at-ocs/06-23-beer-ratings/blob/master/database_class_methods.rb#L46) in other classes, you'll have a problem because `Beer.new` isn't what you'll want for them. Is there something you can call `new` on besides `Beer`, so that the module's method is more universal?

**Comment by david-at-ocs** [comment]
Think I got it this time.
